 const dummyData=[
    { id: 1, firstName: 'Iradukunda', secondName: 'Josue', location:"Gisozi" },
    { id: 2, firstName: 'Nkumbuye', secondName: 'Eden E', location:"Nduba" },
    { id: 4, firstName: 'Mwiza', secondName: 'Henriette', location:"karuruma" },
    { id: 5, firstName: 'Shema', secondName: 'Arnold', location:"kimisagara" },
    { id: 6, firstName: 'Mugisha', secondName: 'David', location:"Masaka" },
    { id: 7, firstName: 'Mugisha ', secondName: 'Blaise', location:"kicukiro" },
    { id: 8, firstName: 'Rutabana', secondName: 'Kelia', location:"Gikondo" },
    { id: 9, firstName: 'Dushime', secondName: 'Herve', location:"kicukiro" },
    { id: 10, firstName: 'Mukiza', secondName: 'Roger', location:"Gisenyi" },
    { id: 11, firstName: 'Kayitare', secondName: 'Diamond', location:"Nyamirambo" },
    { id: 12, firstName: 'Uwurukundo', secondName: 'Joshua', location:"Gatenga" },
    { id: 13, firstName: 'Mugisha', secondName: 'Patrick', location:"Gikondo" },
    { id: 14, firstName: 'Mugisha', secondName: 'Ivan', location:"Kacyiru" },
    { id: 15, firstName: 'Iradukunda', secondName: 'Christelle', location:"Gikondo" },
    { id: 16, firstName: 'Mucyo', secondName: 'Ivan', location:"Gatenga" },
    { id: 17, firstName: 'Ineza', secondName: 'Ines', location:"Gisozi" },
    { id: 18, firstName: 'Isimbi', secondName: 'Giselle', location:"Gatsata" },
    { id: 19, firstName: 'Uwamahoro', secondName: 'Chretien', location:"Gatenga" },
    { id: 20, firstName: 'Mugisha', secondName: 'Patrick', location:"Gikondo" },
    { id: 21, firstName: 'Mugisha', secondName: 'Ivan', location:"Kacyiru" },
    { id: 22, firstName: 'Iradukunda', secondName: 'Christelle', location:"Gikondo" },
    { id: 23, firstName: 'Mucyo', secondName: 'Ivan', location:"Gatenga" },
    { id: 24, firstName: 'Ineza', secondName: 'Ines', location:"Gisozi" },
    { id: 25, firstName: 'Isimbi', secondName: 'Giselle', location:"Gatsata" },
    { id: 26, firstName: 'Uwamahoro', secondName: 'Chretien', location:"Gatenga" },

];
export default dummyData;